version: "3.9"

services:
  # Disable the local DB container since production uses a managed database.
  db:
    image: alpine:latest
    command: echo "Managed database in use; local db container disabled."
    deploy:
      replicas: 0

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    environment:
      DB_NAME: postgres
      DB_USER: driboune
      DB_PASS: nbfZ29yy!4XEUet&Pq*4J%H0c
      DB_HOST: street-utility-db-server.postgres.database.azure.com
      DB_PORT: 5432
    ports:
      - "80:5000"